<?php
/**
 * Enqueue scripts and styles
 *
 * @package Bricks_Child
 */

defined( 'ABSPATH' ) || exit;

/**
 * Enqueue parent and child theme styles and scripts
 *
 * @return void
 */
function bricks_child_enqueue_assets() {
	// Get parent theme version.
	$parent_theme   = wp_get_theme()->parent();
	$parent_version = $parent_theme ? $parent_theme->get( 'Version' ) : '1.0.0';

	// Enqueue parent theme style.
	wp_enqueue_style(
		'bricks-parent',
		get_template_directory_uri() . '/style.css',
		array(),
		$parent_version
	);

	// Get child theme asset file generated by webpack.
	$main_asset_file   = BRICKS_CHILD_DIR . '/assets/dist/main.asset.php';
	$header_asset_file = BRICKS_CHILD_DIR . '/assets/dist/header.asset.php';

	if ( ! file_exists( $main_asset_file ) ) {
		// Fallback if asset file doesn't exist (not built yet).
		wp_enqueue_style(
			'bricks-child',
			BRICKS_CHILD_URI . '/style.css',
			array( 'bricks-parent' ),
			BRICKS_CHILD_VERSION
		);
		return;
	}

	// Load asset file.
	$main_asset   = require $main_asset_file;
	$header_asset = require $header_asset_file;

	// Enqueue child theme compiled CSS.
	wp_enqueue_style(
		'bricks-child',
		BRICKS_CHILD_URI . '/assets/dist/style.css',
		array( 'bricks-parent' ),
		$main_asset['version']
	);

	// Enqueue child theme compiled JS.
	wp_enqueue_script(
		'bricks-child',
		BRICKS_CHILD_URI . '/assets/dist/main.js',
		$main_asset['dependencies'],
		$main_asset['version'],
		true
	);

	// Enqueue child theme compiled header JS.
	wp_enqueue_script(
		'bricks-child-header',
		BRICKS_CHILD_URI . '/assets/dist/header.js',
		$header_asset['dependencies'],
		$header_asset['version'],
		true
	);

	wp_set_script_translations(
		'bricks-child-header',
		'bricks-child',
		BRICKS_CHILD_DIR . '/languages'
	);

	// Localize script with data from PHP.
	wp_localize_script(
		'bricks-child',
		'bricksChildData',
		array(
			'ajaxUrl'      => admin_url( 'admin-ajax.php' ),
			'restUrl'      => rest_url(),
			'nonce'        => wp_create_nonce( 'wp_rest' ),
			'siteUrl'      => home_url(),
			'themeUrl'     => BRICKS_CHILD_URI,
			'currentLang'  => function_exists( 'pll_current_language' ) ? pll_current_language() : substr( get_locale(), 0, 2 ),
			'translations' => array(
				'loading'   => _x( 'Loading...', 'loading status message', 'bricks-child' ),
				'error'     => _x( 'An error occurred', 'error message', 'bricks-child' ),
				'success'   => _x( 'Success!', 'success message', 'bricks-child' ),
				'loadMore'  => _x( 'Load More', 'button text', 'bricks-child' ),
				'noResults' => _x( 'No results found', 'empty state message', 'bricks-child' ),
			),
		)
	);

	if ( is_archive() || is_home() ) {
		$archive_asset_file = BRICKS_CHILD_DIR . '/assets/dist/archive.asset.php';
		$archive_asset      = require $archive_asset_file;

		wp_enqueue_style(
			'bricks-child-archive',
			BRICKS_CHILD_URI . '/assets/dist/archive.css',
			array(),
			$archive_asset['version']
		);
	}

	if ( is_singular() ) {
		$single_asset_file = BRICKS_CHILD_DIR . '/assets/dist/single.asset.php';
		$single_asset      = require $single_asset_file;

		wp_enqueue_style(
			'bricks-child-single',
			BRICKS_CHILD_URI . '/assets/dist/single.css',
			array(),
			$single_asset['version']
		);

		wp_enqueue_script(
			'bricks-child-single-script',
			BRICKS_CHILD_URI . '/assets/dist/single-script.js',
			array(),
			$single_asset['version'],
			true
		);
	}
}
add_action( 'wp_enqueue_scripts', 'bricks_child_enqueue_assets', 20 );

/**
 * Enqueue styles for the block editor
 *
 * @return void
 */
function bricks_child_block_editor_assets() {
	$editor_asset_file = BRICKS_CHILD_DIR . '/assets/dist/style.asset.php';

	if ( ! file_exists( $editor_asset_file ) ) {
		return;
	}

	$editor_asset = require $editor_asset_file;

	// Enqueue block editor styles.
	wp_enqueue_style(
		'bricks-child-editor',
		BRICKS_CHILD_URI . '/assets/dist/style.css',
		array(),
		$editor_asset['version']
	);
}
add_action( 'enqueue_block_editor_assets', 'bricks_child_block_editor_assets' );

/**
 * Add preload for critical assets
 *
 * @return void
 */
function bricks_child_preload_assets() {
	// Preload main CSS.
	echo '<link rel="preload" href="' . esc_url( BRICKS_CHILD_URI . '/assets/dist/style.css' ) . '" as="style">' . "\n";

	// Preload main JS.
	echo '<link rel="preload" href="' . esc_url( BRICKS_CHILD_URI . '/assets/dist/main.js' ) . '" as="script">' . "\n";
}
add_action( 'wp_head', 'bricks_child_preload_assets', 1 );

/**
 * Add async/defer attributes to scripts
 *
 * @param string $tag    The script tag.
 * @param string $handle The script handle.
 * @param string $src    The script source.
 * @return string Modified script tag.
 */
function bricks_child_script_attributes( $tag, $handle, $src ) {
	// Scripts to load async.
	$async_scripts = array();

	// Scripts to defer.
	$defer_scripts = array(
		'bricks-child',
	);

	if ( in_array( $handle, $async_scripts, true ) ) {
		return str_replace( ' src=', ' async src=', $tag );
	}

	if ( in_array( $handle, $defer_scripts, true ) ) {
		return str_replace( ' src=', ' defer src=', $tag );
	}

	return $tag;
}
add_filter( 'script_loader_tag', 'bricks_child_script_attributes', 10, 3 );
